### ISSUE TITLE
Error all commands 

### ISSUE THREAD

**Issue by wladek1909** [segofensiva/OSfooler-ng#4]
This is error when i use all commands, how to fix ? (debian)

`
Traceback (most recent call last):
  File "/usr/local/bin/osfooler-ng", line 11, in <module>
    load_entry_point('OSfooler-ng==1.0a0', 'console_scripts', 'osfooler-ng')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/OSfooler_ng-1.0a0-py3.5.egg/osfooler_ng/osfooler_ng.py", line 465
    print " [+] Fingerprint selected: %s" % l[12:]
                                        ^
SyntaxError: Missing parentheses in call to 'print'
'`

**Comment by moonbaseDelta** [comment]
Seems like you just tried to run it on Python3 instead of Python2 it's made for.
